"""
Plan Verification Module
========================

Verifies that the implementation plan covers all requirements from
requirements.json and additional_requirements.json.

Uses a hybrid approach:
1. If the plan includes a requirements_coverage section (generated by the planner),
   validates it deterministically.
2. If no requirements_coverage exists (legacy plans), falls back to a heuristic
   that checks if requirement keywords appear in subtask descriptions.
"""

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class PlanVerificationResult:
    """Result of plan requirements coverage verification."""

    passed: bool
    coverage_percentage: float
    uncovered_requirements: list[str] = field(default_factory=list)
    details: list[dict] = field(default_factory=list)
    method: str = "structured"  # "structured" or "heuristic"


def _collect_all_requirements(spec_dir: Path) -> list[dict]:
    """
    Collect all requirements from requirements.json and additional_requirements.json.

    Each requirement is returned as:
    {"requirement": "text", "source": "requirements.json|additional_requirements.json"}

    Args:
        spec_dir: Path to the spec directory

    Returns:
        List of requirement dicts
    """
    all_requirements = []

    # Load from requirements.json
    req_file = spec_dir / "requirements.json"
    if req_file.exists():
        try:
            with open(req_file, encoding="utf-8") as f:
                data = json.load(f)

            # User requirements
            for req in data.get("user_requirements", []):
                all_requirements.append(
                    {"requirement": req, "source": "requirements.json"}
                )

            # Acceptance criteria
            for criterion in data.get("acceptance_criteria", []):
                all_requirements.append(
                    {"requirement": criterion, "source": "requirements.json"}
                )

            # If no explicit requirements, use task_description
            if not all_requirements:
                task_desc = data.get("task_description", "")
                if task_desc:
                    all_requirements.append(
                        {"requirement": task_desc, "source": "requirements.json"}
                    )
        except (json.JSONDecodeError, OSError) as e:
            logger.warning(f"Failed to load requirements.json: {e}")

    # Load from additional_requirements.json
    additional_file = spec_dir / "additional_requirements.json"
    if additional_file.exists():
        try:
            with open(additional_file, encoding="utf-8") as f:
                data = json.load(f)

            for req in data.get("requirements", []):
                all_requirements.append(
                    {"requirement": req, "source": "additional_requirements.json"}
                )
        except (json.JSONDecodeError, OSError) as e:
            logger.warning(f"Failed to load additional_requirements.json: {e}")

    return all_requirements


def _verify_structured_coverage(
    plan: dict, all_requirements: list[dict]
) -> PlanVerificationResult:
    """
    Verify requirements coverage using the structured requirements_coverage section.

    The planner is expected to include this section in implementation_plan.json:
    {
      "requirements_coverage": {
        "requirements": [
          {"requirement": "...", "source": "...", "covered_by_subtasks": [...], "status": "covered|uncovered"}
        ],
        "coverage_percentage": 100
      }
    }

    Args:
        plan: The implementation plan dict
        all_requirements: All requirements collected from source files

    Returns:
        PlanVerificationResult
    """
    coverage = plan.get("requirements_coverage", {})
    coverage_reqs = coverage.get("requirements", [])

    if not coverage_reqs:
        # requirements_coverage section exists but is empty
        return PlanVerificationResult(
            passed=False,
            coverage_percentage=0,
            uncovered_requirements=[r["requirement"] for r in all_requirements],
            details=[],
            method="structured",
        )

    # Collect all subtask IDs from the plan for validation
    valid_subtask_ids = set()
    for phase in plan.get("phases", []):
        for subtask in phase.get("subtasks", []):
            valid_subtask_ids.add(subtask.get("id", ""))

    uncovered = []
    details = []

    for entry in coverage_reqs:
        req_text = entry.get("requirement", "")
        covered_by = entry.get("covered_by_subtasks", [])
        status = entry.get("status", "uncovered")

        # Validate that referenced subtask IDs actually exist
        valid_refs = [sid for sid in covered_by if sid in valid_subtask_ids]
        invalid_refs = [sid for sid in covered_by if sid not in valid_subtask_ids]

        is_covered = status == "covered" and len(valid_refs) > 0

        detail = {
            "requirement": req_text,
            "source": entry.get("source", "unknown"),
            "covered_by_subtasks": valid_refs,
            "invalid_subtask_refs": invalid_refs,
            "status": "covered" if is_covered else "uncovered",
        }
        details.append(detail)

        if not is_covered:
            uncovered.append(req_text)

    total = len(coverage_reqs)
    covered_count = total - len(uncovered)
    coverage_pct = (covered_count / total * 100) if total > 0 else 100

    return PlanVerificationResult(
        passed=len(uncovered) == 0,
        coverage_percentage=coverage_pct,
        uncovered_requirements=uncovered,
        details=details,
        method="structured",
    )


def _verify_heuristic_coverage(
    plan: dict, all_requirements: list[dict]
) -> PlanVerificationResult:
    """
    Heuristic fallback: check if requirement keywords appear in subtask descriptions.

    This is used when the plan doesn't have a requirements_coverage section (legacy plans).
    It's less precise but still catches obvious gaps.

    Args:
        plan: The implementation plan dict
        all_requirements: All requirements collected from source files

    Returns:
        PlanVerificationResult
    """
    if not all_requirements:
        return PlanVerificationResult(
            passed=True,
            coverage_percentage=100,
            method="heuristic",
        )

    # Collect all subtask descriptions into a single searchable text
    all_text = ""
    for phase in plan.get("phases", []):
        phase_name = phase.get("name", "")
        phase_desc = phase.get("description", "")
        all_text += f" {phase_name} {phase_desc}"
        for subtask in phase.get("subtasks", []):
            desc = subtask.get("description", "")
            all_text += f" {desc}"

    all_text_lower = all_text.lower()

    uncovered = []
    details = []

    for req_info in all_requirements:
        req = req_info["requirement"]
        # Extract significant words (3+ chars, skip common words)
        words = [
            w.lower()
            for w in req.split()
            if len(w) >= 3
            and w.lower()
            not in {
                "the",
                "and",
                "for",
                "that",
                "this",
                "with",
                "from",
                "should",
                "must",
                "can",
                "will",
                "are",
                "has",
                "have",
                "been",
                "not",
                "all",
            }
        ]

        if not words:
            # Can't meaningfully check this requirement
            details.append(
                {
                    "requirement": req,
                    "source": req_info["source"],
                    "status": "skipped",
                    "reason": "No significant keywords to match",
                }
            )
            continue

        # Check if at least half of significant words appear in subtask text
        matched_words = [w for w in words if w in all_text_lower]
        match_ratio = len(matched_words) / len(words) if words else 0

        is_covered = match_ratio >= 0.5

        details.append(
            {
                "requirement": req,
                "source": req_info["source"],
                "status": "likely_covered" if is_covered else "likely_uncovered",
                "match_ratio": round(match_ratio, 2),
                "matched_keywords": matched_words,
            }
        )

        if not is_covered:
            uncovered.append(req)

    total = len([d for d in details if d["status"] != "skipped"])
    covered_count = total - len(uncovered)
    coverage_pct = (covered_count / total * 100) if total > 0 else 100

    return PlanVerificationResult(
        passed=len(uncovered) == 0,
        coverage_percentage=coverage_pct,
        uncovered_requirements=uncovered,
        details=details,
        method="heuristic",
    )


def verify_plan_requirements_coverage(spec_dir: Path) -> PlanVerificationResult:
    """
    Verify that the implementation plan covers all requirements.

    Uses structured verification if the plan includes requirements_coverage,
    otherwise falls back to heuristic keyword matching.

    Args:
        spec_dir: Path to the spec directory

    Returns:
        PlanVerificationResult with coverage analysis
    """
    plan_file = spec_dir / "implementation_plan.json"
    if not plan_file.exists():
        return PlanVerificationResult(
            passed=False,
            coverage_percentage=0,
            uncovered_requirements=["(plan file not found)"],
            method="structured",
        )

    try:
        with open(plan_file, encoding="utf-8") as f:
            plan = json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        logger.warning(f"Failed to load implementation plan: {e}")
        return PlanVerificationResult(
            passed=False,
            coverage_percentage=0,
            uncovered_requirements=[f"(plan file error: {e})"],
            method="structured",
        )

    # Collect all requirements from source files
    all_requirements = _collect_all_requirements(spec_dir)

    if not all_requirements:
        # No requirements to verify against — pass by default
        logger.info("No requirements found to verify against")
        return PlanVerificationResult(
            passed=True,
            coverage_percentage=100,
            method="structured",
        )

    # Use structured verification if the plan has requirements_coverage
    if "requirements_coverage" in plan and plan["requirements_coverage"]:
        logger.info("Using structured requirements coverage verification")
        return _verify_structured_coverage(plan, all_requirements)

    # Fall back to heuristic
    logger.info("No requirements_coverage in plan — using heuristic verification")
    return _verify_heuristic_coverage(plan, all_requirements)
